services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: course-db
      POSTGRES_HOST: localhost
    ports:
      - 5400:5432
